name: tests
on:
  pull_request: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
          
      - run: |
          set -eux
          curl -o s.tgz -L https://github.com/sshst/sshststuff/releases/download/0.17/sshst_0.17_Linux_x86_64.tar.gz
          tar -xvf s.tgz
          ./sshst listen -g aidansteele --web-ok --notify-user aidansteele
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: setup
        run: |
          set -eux
          go build -o sshst ./cmd
          ./sshst setup | sh

      - name: test
        run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
